#!/bin/bash
# skript, mis ksib kasutaja nime ja tervitab 
echo –n “Sisesta oma ees- ja perenimi: ”
read eesnimi perenimi
echo “Sinu eesnimi on $eesnimi ja perenimi on $perenimi” 
echo -n "Tere tulemast, $eesnimi $perenimi"
echo !
#

