#!/bin/bash
#
#reisi korraldamine
#
  echo -n "Sisesta reisjate arv: "
read reisjad
# kohtade andmed bussis
echo -n "sisesta kohtade arv bussis: "
read kohad
#
#arvutused
#
#jagame inimesed busside vahel nii, et koik kohad bussides oleks taidetud, saame teada, kui suurt bussi vaja
bussid=$(($reisijad % $kohad))
#
#ulejaanud tuleb suurendada busside arv 1 vorra
if test $ylejaanud -gt 0
 then bussid=$(($bussid
